version: '3'
volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: salasana
      MYSQL_DATABASE: chatti_db
      MYSQL_USER: root
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"